### ISSUE TITLE
Database doesn't import and causes a crash

### ISSUE THREAD

**Issue by Syntax-Err5** [25huizengek1/ViTune#268]
### Steps to reproduce the bug

1. Export db from ViTune 1.0.3
2. Import to latest nightly build
3. Nightly build crashes and db is not imported (and everything that was there is wiped)

### Expected behavior

Database imports songs and playlists from stable to nightly build. 

### Actual behavior

App crashes, db not imported

### Logs

FATAL EXCEPTION: arch_disk_io_2
Process: app.vitune.android.nightly, PID: 26244
android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11 SQLITE_CORRUPT)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1030)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:145)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at M2.r.J(SourceFile:37)
	at Q2.v.a(SourceFile:13)
	at Q2.v.e(SourceFile:43)
	at r0.v.run(SourceFile:27)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### ViTune version

1.0.3

### What kind of build are you using?

Nightly (F-Droid)

### Android version

Android 13

### Device info

Oppo A54 5g, running ColorOS 13

### Additional information

This issue has been reported multiple times already, but hopefully the logs with help

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Syntax-Err5** [comment]
Here is the db file btw:
[ViTune_backup_20240506171637.zip](https://github.com/25huizengek1/ViTune/files/15218208/ViTune_backup_20240506171637.zip)

**Comment by Enigma1309** [comment]
![image](https://github.com/25huizengek1/ViTune/assets/94917588/7d84c22f-736f-417f-919f-c442e8e7873a)

**Comment by Syntax-Err5** [comment]
Woah thanks for pointing that out, I didnt realise it backed that up too
Changing my password 😅

**Comment by Syntax-Err5** [comment]
Here's a new db with the same problem:
[ViTune_backup_20240509172054.zip](https://github.com/25huizengek1/ViTune/files/15259383/ViTune_backup_20240509172054.zip)

**Comment by 25huizengek1** [comment]
> Woah thanks for pointing that out, I didnt realise it backed that up too Changing my password 😅

Funny thing is that I already considered something like this would happen with Piped accounts, yet still I haven't changed anything about the way this works. Maybe something for a separate issue ticket?

**Comment by 25huizengek1** [comment]
Now for the error, I guess this has something to do with the fact that I update the Room dependency every now and then, which may cause some unexpected behavior like this. I'll try to find out why this is after my final exams, because this seems a bit complicated.

**Comment by fakeworldxd** [comment]
I am also unable to restore data from vitune db file, on 1.0.4
But I was able to restore data from an older vimusic db onto vitune 1.0.4 
I've tried this again with music you (another fork of vimusic) and it behaved in the same way
Guess I'll stick using the old db until the fix comes out 😅

Also I hope to see a system which allows vitune db to be compatible with other vimusic forks (if possible) - I believe it can be done by letting the user choose what data to backup at the time of backup instead of backing up all data

**Comment by 25huizengek1** [comment]
> I believe it can be done by letting the user choose what data to backup at the time of backup instead of backing up all data

Interesting idea, I think letting users export for ViMusic v0.5.4 and calling it 'compat mode' should do the trick, no?

**Comment by Enigma1309** [comment]
> Interesting idea, I think letting users export for ViMusic v0.5.4 and calling it 'compat mode' should do the trick, no?

yeah and also i suggest to remove the piped credentials from the db.

**Comment by fakeworldxd** [comment]
> > I believe it can be done by letting the user choose what data to backup at the time of backup instead of backing up all data
> 
> Interesting idea, I think letting users export for ViMusic v0.5.4 and calling it 'compat mode' should do the trick, no?

Yeah, I think that'll work.

**Comment by davidpkj** [comment]
Hi, I don't know if it's relevant but thought I'd share:

Had the same problem on a new install. Then (after trying around for a while) I first cleared all app data in android settings and then played a random suggested song for a few seconds and tried importing again. Then importing worked flawlessly. Both versions of the app (export and import side) were 1.0.4.

Maybe playing a song initialized someting somewhere...? Anyway hope it helps.

**Comment by NeeRaj-2401** [comment]
> Had the same problem on a new install. Then (after trying around for a while) I first cleared all app data in android settings and then played a random suggested song for a few seconds and tried importing again. Then importing worked flawlessly.

Didn't worked for me, recently i did a fresh install and tried to restore from nightly build backup db, app just closes and nothing happens after reopening 

Also i tried to do setup again, with a fresh backup db and tried to restore that, same results

**Comment by awwRoar** [comment]
**Workaround for v1.1.1 app foreclosure after importing db:**

Import database to the app from external storage -> App crashes -> Switch off internet -> Open ViTune and go to the Local (last one) section -> Grant storage permission again if it prompts -> Switch to Songs / Playlists section to check if your db has been added (without thumbnails) -> Switch on internet -> End

This worked for me today.
