### ISSUE TITLE
Opening settings menu results in crash

### ISSUE THREAD

**Issue by TicTecOfficial** [25huizengek1/ViTune#404]
### Steps to reproduce the bug

Open ViTune
Press the gear icon on the top left

### Expected behavior

The settings menu should open up as expected and should.

### Actual behavior

The app instantly crashed upon pressing the gear icon/opening the settings menu.

### Logs

FATAL EXCEPTION: main
Process: app.vitune.android, PID: 29784
java.lang.IllegalStateException: Provided signatures did not match. Actual signatures of package are:
listOf(listOf(byteArrayOf(48,-126,3,97,48,-126,2,73,-96,3,2,1,2,2,4,56,-116,78,10,48,13,6,9,42,-122,72,-122,-9,13,1,1,11,5,0,48,97,49,11,48,9,6,3,85,4,6,19,2,56,54,49,16,48,14,6,3,85,4,8,19,7,74,105,97,110,103,115,117,49,14,48,12,6,3,85,4,7,19,5,67,104,105,110,97,49,16,48,14,6,3,85,4,10,19,7,80,114,105,118,97,116,101,49,16,48,14,6,3,85,4,11,19,7,67,104,97,114,108,101,115,49,12,48,10,6,3,85,4,3,19,3,76,101,101,48,30,23,13,50,50,48,52,50,53,48,49,51,57,53,53,90,23,13,52,55,48,52,49,57,48,49,51,57,53,53,90,48,97,49,11,48,9,6,3,85,4,6,19,2,56,54,49,16,48,14,6,3,85,4,8,19,7,74,105,97,110,103,115,117,49,14,48,12,6,3,85,4,7,19,5,67,104,105,110,97,49,16,48,14,6,3,85,4,10,19,7,80,114,105,118,97,116,101,49,16,48,14,6,3,85,4,11,19,7,67,104,97,114,108,101,115,49,12,48,10,6,3,85,4,3,19,3,76,101,101,48,-126,1,34,48,13,6,9,42,-122,72,-122,-9,13,1,1,1,5,0,3,-126,1,15,0,48,-126,1,10,2,-126,1,1,0,-92,71,-37,127,-20,70,107,29,73,113,-71,2,-55,71,24,-87,106,-51,-63,79,39,23,76,-43,104,-111,94,112,-30,-25,-58,-68,53,-126,12,-72,81,-99,92,-116,-112,-6,-116,-69,-95,-118,-31,120,-48,-127,33,-64,37,-4,82,-126,-25,53,84,65,49,-90,-27,95,74,101,-87,-128,-93,46,-83,122,-33,121,84,80,-46,-29,21,30,68,104,-90,17,-19,85,-52,124,-67,-78,-65,121,-24,-71,78,-43,-57,68,8,75,8,32,-70,-116,68,-97,-72,24,-8,54,-79,108,-11,-116,68,86,11,-1,-123,-95,52,-51,-76,51,98,-75,53,65,109,-95,-17,-53,-120,26,-69,26,-124,-122,-17,108,89,80,-74,17,42,-100,-6,104,-125,29,-101,79,-37,-1,120,58,-89,-7,-119,60,54,78,0,10,-35,83,-46,-86,31,-2,11,-34,-89,-105,76,31,57,31,-88,107,72,-62,4,34,-9,-74,67,-42,-17,-89,-109,-107,54,126,96,-44,110,62,-56,90,59,-8,87,92,-24,-59,-122,2,114,-14,-90,-128,-28,-102,114,-117,13,-1,-75,114,-122,-106,-39,-91,-100,-8,-121,-13,-85,68,-95,6,16,-50,57,52,37,-82,104,9,29,-45,115,-110,-46,-126,-96,-108,41,-44,64,-113,10,25,-83,71,2,3,1,0,1,-93,33,48,31,48,29,6,3,85,29,14,4,22,4,20,-34,-58,28,-94,126,67,116,-54,-27,-64,-26,-3,74,-43,11,-46,67,-80,35,18,48,13,6,9,42,-122,72,-122,-9,13,1,1,11,5,0,3,-126,1,1,0,93,68,66,82,80,16,5,73,86,-20,-81,-94,-36,-35,42,97,-65,50,-67,-102,-126,29,-80,-111,61,-51,-61,-29,90,78,47,75,92,90,90,67,-99,28,-30,-42,-74,84,-45,9,116,77,-29,-73,38,97,-68,-113,85,78,2,91,71,94,94,59,20,77,79,-91,-99,-48,77,-117,51,10,81,-95,55,113,15,127,14,-91,90,78,117,53,-97,8,-2,-84,-55,-72,-10,122,-23,40,-34,78,81,102,63,19,-128,-114,83,-29,19,-39,-59,-119,-57,5,-112,86,-28,80,32,-10,-13,-59,94,-11,65,117,-97,-32,-83,87,95,-62,-26,52,-72,14,121,-107,103,58,-38,43,-111,-91,111,-3,-122,-54,-74,-99,60,89,-92,-96,127,65,-55,-87,-33,-61,75,14,-112,26,-82,1,-35,122,-85,115,-58,60,87,-125,118,18,-34,22,-16,35,43,52,120,41,-92,21,113,-123,90,-79,13,76,46,-25,21,4,114,-125,-27,-78,-92,-69,-104,-86,-5,124,-63,12,-113,-39,-30,-124,-91,-99,-72,15,21,66,-60,26,36,-57,-93,-101,-42,-103,-17,-81,11,-83,-39,-38,42,107,119,-38,-86,-82,-53,-118,-7,-101,-14,-76,69,65,-113,-83,37,10,88,62,-104,-9,55,5,54,-7,-76,81,-98,-127)))
	at B3.r.d(SourceFile:2203)
	at S.a.b(SourceFile:44)
	at S.a.d(SourceFile:9)
	at h3.f.l(SourceFile:285)
	at H3.h.d(SourceFile:117)
	at S.a.b(SourceFile:44)
	at S.a.d(SourceFile:9)
	at h3.f.h(SourceFile:384)
	at Y3.c.d(SourceFile:86)
	at H3.V.invoke(SourceFile:184)
	at S.a.invoke(SourceFile:52)
	at K.q.a(SourceFile:219)
	at T.g.f(SourceFile:96)
	at H3.W.l(SourceFile:88)
	at S.a.e(SourceFile:44)
	at S.a.l(SourceFile:9)
	at B.N.d(SourceFile:117)
	at S.a.b(SourceFile:44)
	at S.a.d(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1266)
	at s.e.invoke(SourceFile:272)
	at S.a.invoke(SourceFile:52)
	at K6.t.b(SourceFile:936)
	at K6.t.a(SourceFile:236)
	at K6.t.i(SourceFile:886)
	at H3.X.d(SourceFile:194)
	at S.a.b(SourceFile:44)
	at S.a.d(SourceFile:9)
	at M3.r.l(SourceFile:328)
	at S.a.e(SourceFile:44)
	at S.a.l(SourceFile:9)
	at B.N.d(SourceFile:117)
	at S.a.b(SourceFile:44)
	at S.a.d(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1266)
	at s.e.invoke(SourceFile:272)
	at S.a.invoke(SourceFile:52)
	at K6.t.b(SourceFile:936)
	at M3.s.a(SourceFile:371)
	at M3.s.b(SourceFile:189)
	at h3.f.n(SourceFile:88)
	at v3.c.invoke(SourceFile:26)
	at S.a.invoke(SourceFile:52)
	at M3.h.c(SourceFile:93)
	at v3.f.a(SourceFile:90)
	at B3.r.d(SourceFile:84)
	at S.a.b(SourceFile:44)
	at S.a.d(SourceFile:9)
	at M3.r.l(SourceFile:328)
	at S.a.e(SourceFile:44)
	at S.a.l(SourceFile:9)
	at B.N.d(SourceFile:117)
	at S.a.b(SourceFile:44)
	at S.a.d(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1266)
	at s.e.invoke(SourceFile:272)
	at S.a.invoke(SourceFile:52)
	at K6.t.b(SourceFile:936)
	at M3.s.a(SourceFile:371)
	at M3.s.b(SourceFile:189)
	at s3.p.invoke(SourceFile:47)
	at K.p.L(SourceFile:483)
	at K.p.S(SourceFile:58)
	at K.p.r(SourceFile:158)
	at K.p.J(SourceFile:29)
	at K.u.v(SourceFile:36)
	at K.u0.s(SourceFile:112)
	at K.s0.invoke(SourceFile:377)
	at K.z.doFrame(SourceFile:14)
	at s0.T.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1278)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:907)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
	Suppressed: Y6.g: [K.h0@5f17609, s0.q0@dbc300e, x0{Cancelling}@898ea2f, U@fd0383c]

### ViTune version

v1.0.6-RELEASE

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 12

### Device info

I'm using the Huawei Mate 30 Pro, on EMUI 12.0.0.355, with the chipset Kirin 990 5G.

### Upstream reproducibility

This issue does NOT occur in the latest stable release of ViMusic.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Apparently, checking whether Google Fonts is available crashes if it isn't. This check happens in settings, let me patch this.

**Comment by TicTecOfficial** [comment]
hey there, appreciate your response and immediate action for it.

is the patched .apk already compiled or do i still have to compile it myself? i tried compiling it but that resulted in an error i may need to look into or something.

**Comment by 25huizengek1** [comment]
Here you go:

https://www.dropbox.com/scl/fi/l63chwv8uzh8rehoglyts/app.vitune.android_patch08092024.apk?rlkey=xhaeabuk9p2wk2b8s0fsnzbq9&st=0kdszkz0&dl=0

**Comment by TicTecOfficial** [comment]
hi there, not sure if this is the same error but even after using the patch it still crashes in the same way:

FATAL EXCEPTION: main
Process: app.vitune.android, PID: 6104
java.lang.IllegalStateException: Provided signatures did not match. Actual signatures of package are:
listOf(listOf(byteArrayOf(48,-126,3,97,48,-126,2,73,-96,3,2,1,2,2,4,56,-116,78,10,48,13,6,9,42,-122,72,-122,-9,13,1,1,11,5,0,48,97,49,11,48,9,6,3,85,4,6,19,2,56,54,49,16,48,14,6,3,85,4,8,19,7,74,105,97,110,103,115,117,49,14,48,12,6,3,85,4,7,19,5,67,104,105,110,97,49,16,48,14,6,3,85,4,10,19,7,80,114,105,118,97,116,101,49,16,48,14,6,3,85,4,11,19,7,67,104,97,114,108,101,115,49,12,48,10,6,3,85,4,3,19,3,76,101,101,48,30,23,13,50,50,48,52,50,53,48,49,51,57,53,53,90,23,13,52,55,48,52,49,57,48,49,51,57,53,53,90,48,97,49,11,48,9,6,3,85,4,6,19,2,56,54,49,16,48,14,6,3,85,4,8,19,7,74,105,97,110,103,115,117,49,14,48,12,6,3,85,4,7,19,5,67,104,105,110,97,49,16,48,14,6,3,85,4,10,19,7,80,114,105,118,97,116,101,49,16,48,14,6,3,85,4,11,19,7,67,104,97,114,108,101,115,49,12,48,10,6,3,85,4,3,19,3,76,101,101,48,-126,1,34,48,13,6,9,42,-122,72,-122,-9,13,1,1,1,5,0,3,-126,1,15,0,48,-126,1,10,2,-126,1,1,0,-92,71,-37,127,-20,70,107,29,73,113,-71,2,-55,71,24,-87,106,-51,-63,79,39,23,76,-43,104,-111,94,112,-30,-25,-58,-68,53,-126,12,-72,81,-99,92,-116,-112,-6,-116,-69,-95,-118,-31,120,-48,-127,33,-64,37,-4,82,-126,-25,53,84,65,49,-90,-27,95,74,101,-87,-128,-93,46,-83,122,-33,121,84,80,-46,-29,21,30,68,104,-90,17,-19,85,-52,124,-67,-78,-65,121,-24,-71,78,-43,-57,68,8,75,8,32,-70,-116,68,-97,-72,24,-8,54,-79,108,-11,-116,68,86,11,-1,-123,-95,52,-51,-76,51,98,-75,53,65,109,-95,-17,-53,-120,26,-69,26,-124,-122,-17,108,89,80,-74,17,42,-100,-6,104,-125,29,-101,79,-37,-1,120,58,-89,-7,-119,60,54,78,0,10,-35,83,-46,-86,31,-2,11,-34,-89,-105,76,31,57,31,-88,107,72,-62,4,34,-9,-74,67,-42,-17,-89,-109,-107,54,126,96,-44,110,62,-56,90,59,-8,87,92,-24,-59,-122,2,114,-14,-90,-128,-28,-102,114,-117,13,-1,-75,114,-122,-106,-39,-91,-100,-8,-121,-13,-85,68,-95,6,16,-50,57,52,37,-82,104,9,29,-45,115,-110,-46,-126,-96,-108,41,-44,64,-113,10,25,-83,71,2,3,1,0,1,-93,33,48,31,48,29,6,3,85,29,14,4,22,4,20,-34,-58,28,-94,126,67,116,-54,-27,-64,-26,-3,74,-43,11,-46,67,-80,35,18,48,13,6,9,42,-122,72,-122,-9,13,1,1,11,5,0,3,-126,1,1,0,93,68,66,82,80,16,5,73,86,-20,-81,-94,-36,-35,42,97,-65,50,-67,-102,-126,29,-80,-111,61,-51,-61,-29,90,78,47,75,92,90,90,67,-99,28,-30,-42,-74,84,-45,9,116,77,-29,-73,38,97,-68,-113,85,78,2,91,71,94,94,59,20,77,79,-91,-99,-48,77,-117,51,10,81,-95,55,113,15,127,14,-91,90,78,117,53,-97,8,-2,-84,-55,-72,-10,122,-23,40,-34,78,81,102,63,19,-128,-114,83,-29,19,-39,-59,-119,-57,5,-112,86,-28,80,32,-10,-13,-59,94,-11,65,117,-97,-32,-83,87,95,-62,-26,52,-72,14,121,-107,103,58,-38,43,-111,-91,111,-3,-122,-54,-74,-99,60,89,-92,-96,127,65,-55,-87,-33,-61,75,14,-112,26,-82,1,-35,122,-85,115,-58,60,87,-125,118,18,-34,22,-16,35,43,52,120,41,-92,21,113,-123,90,-79,13,76,46,-25,21,4,114,-125,-27,-78,-92,-69,-104,-86,-5,124,-63,12,-113,-39,-30,-124,-91,-99,-72,15,21,66,-60,26,36,-57,-93,-101,-42,-103,-17,-81,11,-83,-39,-38,42,107,119,-38,-86,-82,-53,-118,-7,-101,-14,-76,69,65,-113,-83,37,10,88,62,-104,-9,55,5,54,-7,-76,81,-98,-127)))
	at B3.J0.f(SourceFile:1767)
	at S.a.a(SourceFile:44)
	at S.a.f(SourceFile:9)
	at b3.t.j(SourceFile:279)
	at J3.g.f(SourceFile:119)
	at S.a.a(SourceFile:44)
	at S.a.f(SourceFile:9)
	at b3.t.f(SourceFile:377)
	at a3.B.a(SourceFile:86)
	at A3.c.invoke(SourceFile:131)
	at S.a.invoke(SourceFile:52)
	at K.p.a(SourceFile:213)
	at T.g.e(SourceFile:96)
	at A3.d.k(SourceFile:52)
	at S.a.c(SourceFile:44)
	at S.a.k(SourceFile:9)
	at B.L.f(SourceFile:117)
	at S.a.a(SourceFile:44)
	at S.a.f(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1267)
	at s.e.invoke(SourceFile:270)
	at S.a.invoke(SourceFile:52)
	at J6.a.b(SourceFile:932)
	at J6.a.a(SourceFile:236)
	at a4.c.m(SourceFile:891)
	at A3.e.f(SourceFile:98)
	at S.a.a(SourceFile:44)
	at S.a.f(SourceFile:9)
	at O3.q.k(SourceFile:334)
	at S.a.c(SourceFile:44)
	at S.a.k(SourceFile:9)
	at B.L.f(SourceFile:117)
	at S.a.a(SourceFile:44)
	at S.a.f(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1267)
	at s.e.invoke(SourceFile:270)
	at S.a.invoke(SourceFile:52)
	at J6.a.b(SourceFile:932)
	at O3.r.a(SourceFile:390)
	at O3.r.b(SourceFile:211)
	at b3.t.l(SourceFile:112)
	at x3.c.invoke(SourceFile:26)
	at S.a.invoke(SourceFile:52)
	at O3.g.d(SourceFile:93)
	at x3.f.a(SourceFile:88)
	at B3.J0.f(SourceFile:2835)
	at S.a.a(SourceFile:44)
	at S.a.f(SourceFile:9)
	at O3.q.k(SourceFile:334)
	at S.a.c(SourceFile:44)
	at S.a.k(SourceFile:9)
	at B.L.f(SourceFile:117)
	at S.a.a(SourceFile:44)
	at S.a.f(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1267)
	at s.e.invoke(SourceFile:270)
	at S.a.invoke(SourceFile:52)
	at J6.a.b(SourceFile:932)
	at O3.r.a(SourceFile:390)
	at O3.r.b(SourceFile:211)
	at u3.o.invoke(SourceFile:40)
	at K.o.H(SourceFile:483)
	at K.o.N(SourceFile:58)
	at K.o.p(SourceFile:160)
	at K.o.G(SourceFile:29)
	at K.t.u(SourceFile:36)
	at K.v0.r(SourceFile:104)
	at K.t0.invoke(SourceFile:372)
	at K.z.doFrame(SourceFile:14)
	at s0.T.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1278)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:907)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
	Suppressed: c7.g: [K.h0@de1786a, s0.p0@7acc15b, w0{Cancelling}@eda3df8, U@79e22d1]

**Comment by 25huizengek1** [comment]
I'm sorry, I sent the wrong APK, I'll release a new version of the app soon.

**Comment by 25huizengek1** [comment]
@TicTecOfficial I've checked it now that I'm at my pc again, it was a build from 11:41, and I patched this issue at 11:45, so that explains this
