### ISSUE TITLE
Swipe to go back crashing the app in some cases.

### ISSUE THREAD

**Issue by Megafrox** [25huizengek1/ViTune#449]
### Steps to reproduce the bug

Scroll down to older searches in the search menu, click on one, than swipe in from the side to go back.

### Expected behavior

It should go back to the search tab.

### Actual behavior

The app crashes.

### ViTune version

v1.0.9

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

android 14

### Device info

Pixel 6a, not sure exactly which version, but should be the latest android 14 release.

### Additional information

I have a video, but it was too big to upload here. If anyone knows how to get around this, I can post that aswell.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
@Megafrox Do you have predictive back enabled? It seems that messes with a lot of the routing code.

**Comment by 25huizengek1** [comment]
Alright, that clears up a lot of the confusion on why this could happen. Can you please provide some crash logs?

**Comment by Megafrox** [comment]
> Alright, that clears up a lot of the confusion on why this could happen. Can you please provide some crash logs?

I'm not very good with this kind of stuff, so I don't really know how to see the logs.

**Comment by Syntax-Err5** [comment]
I can reproduce this on a Pixel 9 with Android 14:

FATAL EXCEPTION: main
Process: app.vitune.android, PID: 4207
java.lang.IllegalStateException:
   FocusRequester is not initialized. Here are some possible fixes:
   1. Remember the FocusRequester: val focusRequester = remember { FocusRequester() }
   2. Did you forget to add a Modifier.focusRequester() ?
   3. Are you attempting to request focus during composition? Focus requests should be made in
   response to some event. Eg Modifier.clickable { focusRequester.requestFocus() }
	at f0.n.a(SourceFile:223)
	at f0.n.b(SourceFile:3)
	at S3.j.m(SourceFile:38)
	at Q6.a.o(SourceFile:9)
	at n7.I.run(SourceFile:113)
	at A0.x0.Q(SourceFile:7)
	at A0.w0.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: s7.g: [A0.a1@2333cbb, O.g@ff405d8, w0{Cancelling}@1be7d31, x0@d266c16]
