### ISSUE TITLE
App is crashing in A15

### ISSUE THREAD

**Issue by rishikeishkannan** [25huizengek1/ViTune#655]
I was using this app for quite a while , but I recently upgraded to A15 and to my surprise the app isn't opening at all it crashes.

**Comment by 25huizengek1** [comment]
I'm on Android 15 and it works. Please attach some crash logs.

**Comment by sachinz25** [comment]
time: 1735375246686
msg: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
stacktrace: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
	at android.graphics.Bitmap.createBitmap(Bitmap.java:932)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:854)
	at android.media.MediaMetadata$Builder.scaleBitmap(MediaMetadata.java:988)
	at android.media.MediaMetadata$Builder.build(MediaMetadata.java:970)
	at android.media.session.MediaSession.setMetadata(MediaSession.java:512)
	at A3.D.run(SourceFile:201)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

here is crash log on A15

**Comment by rishikeishkannan** [comment]
I'm noob , how to get crash logs ? I used matlib once but now it says it's not supported

**Comment by 25huizengek1** [comment]
It seems like some folks are still getting recycled bitmaps (even when ViTune now checks whether bitmaps are recycled)

**Comment by sachinz25** [comment]
yes, version 1.1.2-RELEASE getting same errors.

ViTune version
v1.1.2

What kind of build are you using?
Release (GitHub)

Android version
Android 15

Device info
Redmi note 10 pro max(sweetin) with project infinity-X custom rom.

Logs:
time: 1736961761197
msg: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
stacktrace: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
	at android.graphics.Bitmap.createBitmap(Bitmap.java:932)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:854)
	at android.media.MediaMetadata$Builder.scaleBitmap(MediaMetadata.java:988)
	at android.media.MediaMetadata$Builder.build(MediaMetadata.java:970)
	at android.media.session.MediaSession.setMetadata(MediaSession.java:512)
	at A3.D.run(SourceFile:201)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by GuckicheLorraine** [comment]
> It seems like some folks are still getting recycled bitmaps (even when ViTune now checks whether bitmaps are recycled)

How do we get rid of those recycled beatmaps causing the issue (if I understood correctly).
Because I just updated to ViTune v.1.1.5 and the app still crashes at launch.

**Comment by hobyhop** [comment]
Clearing cache and data for the app does not help.
I'm on a clean install of crdroid 11.4

**Comment by hobyhop** [comment]
Same in 1.1.5:
time: 1747330875265
msg: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
stacktrace: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
	at android.graphics.Bitmap.createBitmap(Bitmap.java:942)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:864)
	at android.media.MediaMetadata$Builder.scaleBitmap(MediaMetadata.java:996)
	at android.media.MediaMetadata$Builder.build(MediaMetadata.java:970)
	at android.media.session.MediaSession.setMetadata(MediaSession.java:512)
	at K3.r.run(SourceFile:171)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8934)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
[GitHub](https://github.com/lus/pasty)

**Comment by gauravsuvarna** [comment]
> yes, version 1.1.2-RELEASE getting same errors.
> 
> ViTune version
> v1.1.2
> 
> What kind of build are you using?
> Release (GitHub)
> 
> Android version
> Android 15
> 
> Device info
> Redmi note 10 pro max(sweetin) with project infinity-X custom rom.
> 
> Logs:
> time: 1736961761197
> msg: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
> stacktrace: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
> 	at android.graphics.Bitmap.createBitmap(Bitmap.java:932)
> 	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:854)
> 	at android.media.MediaMetadata$Builder.scaleBitmap(MediaMetadata.java:988)
> 	at android.media.MediaMetadata$Builder.build(MediaMetadata.java:970)
> 	at android.media.session.MediaSession.setMetadata(MediaSession.java:512)
> 	at A3.D.run(SourceFile:201)
> 	at android.os.Handler.handleCallback(Handler.java:959)
> 	at android.os.Handler.dispatchMessage(Handler.java:100)
> 	at android.os.Looper.loopOnce(Looper.java:232)
> 	at android.os.Looper.loop(Looper.java:317)
> 	at android.app.ActivityThread.main(ActivityThread.java:8706)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)





In project infinity 2.5(Android15) it works, am using that,but in 2.8 it doesn't.

**Comment by 25huizengek1** [comment]
ViTune is going into maintenance mode. Only security (or related) issues will be accepted. All current open issues are being closed.
