### ISSUE TITLE
App not opening 

### ISSUE THREAD

**Issue by JustRandomboy** [25huizengek1/ViTune#672]
### Steps to reproduce the bug

When click the app it crashed immediately

### Expected behavior

App not opening 

### Actual behavior

App not opening 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/1afcbae8-c463-419e-8c15-11457cd7f00e

### Logs

https://paste.evolution-x.org/q1ZmmA

time: 1735440516283
msg: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
stacktrace: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
	at android.graphics.Bitmap.createBitmap(Bitmap.java:932)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:854)
	at android.media.MediaMetadata$Builder.scaleBitmap(MediaMetadata.java:996)
	at android.media.MediaMetadata$Builder.build(MediaMetadata.java:970)
	at android.media.session.MediaSession.setMetadata(MediaSession.java:512)
	at A3.D.run(SourceFile:201)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8788)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:

### ViTune version

V1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

15

### Device info

Poco f5 

### Additional information

It should open 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Duplicate of #655

**Comment by JustRandomboy** [comment]
Any solution for that ?

**Comment by 25huizengek1** [comment]
I fixed it for the next release.

**Comment by JustRandomboy** [comment]
Same problem again in the new update

**Comment by JustRandomboy** [comment]
https://github.com/user-attachments/assets/34854a04-03b3-478a-928a-782078049f8f

**Comment by JustRandomboy** [comment]
https://paste.evolution-x.org/51Tbz6
